-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=host.docker.internal;service_name=FREEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;





CREATE OR REPLACE PROCEDURE get_employee (p_id bigint, p_name INOUT text) AS $body$
BEGIN
    SELECT name INTO STRICT p_name FROM dev_user.employees WHERE id = p_id;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE get_employee (p_id bigint, p_name INOUT text) FROM PUBLIC;





CREATE OR REPLACE PROCEDURE process_annual_raises ( p_dept_id bigint, p_raise_percent bigint, p_total_cost INOUT bigint ) AS $body$
DECLARE

    -- Explicit Cursor
    emp_cur CURSOR FOR
        SELECT emp_id, salary, hire_date
        FROM erp_employees
        WHERE dept_id = p_dept_id AND status = 'ACTIVE';

    v_new_salary bigint;
    v_years_worked bigint;
    v_accumulated_cost bigint := 0;
BEGIN
    -- Loop through the cursor
    FOR emp_rec IN emp_cur LOOP
        -- Oracle-specific date math (TRUNC and MONTHS_BETWEEN)
        v_years_worked := date_trunc('day', MONTHS_BETWEEN(clock_timestamp(), emp_rec.hire_date) / 12);

        IF v_years_worked > 5 THEN
            v_new_salary := emp_rec.salary + (emp_rec.salary * (p_raise_percent / 100)) + 1000; -- Loyalty bonus
        ELSE
            v_new_salary := emp_rec.salary + (emp_rec.salary * (p_raise_percent / 100));
        END IF;

        -- Update the record
        UPDATE erp_employees
        SET salary = v_new_salary
        WHERE emp_id = emp_rec.emp_id;

        v_accumulated_cost := v_accumulated_cost + (v_new_salary - emp_rec.salary);
    END LOOP;

    -- Oracle's NVL function to handle nulls
    p_total_cost := coalesce(v_accumulated_cost, 0);
    COMMIT;

EXCEPTION
    WHEN no_data_found THEN
        p_total_cost := 0;
        RAISE NOTICE 'No active employees found in department.';
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE process_annual_raises ( p_dept_id bigint, p_raise_percent bigint, p_total_cost INOUT bigint ) FROM PUBLIC;

