-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=host.docker.internal;service_name=FREEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;





CREATE OR REPLACE PROCEDURE get_employee (p_id bigint, p_name INOUT text) AS $body$
BEGIN
    SELECT name INTO STRICT p_name FROM dev_user.employees WHERE id = p_id;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE get_employee (p_id bigint, p_name INOUT text) FROM PUBLIC;

