-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=host.docker.internal;service_name=FREEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;



CREATE TABLE employees (
	id bigint NOT NULL,
	name varchar(100),
	hired_date timestamp(0) DEFAULT statement_timestamp()
) ;
ALTER TABLE employees ADD PRIMARY KEY (id);
