-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=host.docker.internal;service_name=FREEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;



CREATE TABLE employees (
	id bigint NOT NULL,
	name varchar(100),
	hired_date timestamp(0) DEFAULT statement_timestamp()
) ;
ALTER TABLE employees ADD PRIMARY KEY (id);


CREATE TABLE erp_departments (
	dept_id bigint NOT NULL,
	dept_name varchar(50) NOT NULL,
	annual_budget bigint DEFAULT 0
) ;
ALTER TABLE erp_departments ADD PRIMARY KEY (dept_id);
ALTER TABLE erp_departments ALTER COLUMN dept_name SET NOT NULL;


CREATE TABLE erp_employees (
	emp_id bigint NOT NULL,
	name varchar(100),
	hire_date timestamp(0) DEFAULT statement_timestamp(),
	salary decimal(10,2),
	dept_id bigint,
	status varchar(20) DEFAULT 'ACTIVE'
) ;
ALTER TABLE erp_employees ADD PRIMARY KEY (emp_id);
ALTER TABLE erp_employees ADD CONSTRAINT sys_c008550 FOREIGN KEY (dept_id) REFERENCES erp_departments(dept_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
