-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=host.docker.internal;service_name=FREEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS emp_bir ON erp_employees CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_emp_bir() RETURNS trigger AS $BODY$
BEGIN
  SELECT nextval('emp_seq') INTO STRICT NEW.emp_id;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER emp_bir
	BEFORE INSERT ON erp_employees FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_emp_bir();

